sudo: required
dist: trusty
language: node_js
node_js: 8.11
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - travis_retry npm install -g polymer-cli web-component-tester
  - travis_retry npm install
script:
  - travis_retry xvfb-run npm test
